p8105\_hw1\_fs2757.Rm
================
FEI SUN
2021/9/21

### Problem 1

-   Create a data frame comprised of:
    -   a random sample of size 10 from a standard Normal distribution
    -   a logical vector indicating whether elements of the sample are
        greater than 0
    -   a character vector of length 10
    -   a factor vector of length 10, with 3 different factor “levels”

``` r
set.seed(1)

P1_df = tibble(
  random_sample = rnorm(10),
  sample_logical = c(random_sample > 0),
  character_vector= c("circle","quadrangle","Triangular","rectangle","trapezoid", "square","oval","conical","hexagon","Egg-Shaped"),
  factor_vector= factor(c("S", "S","S","M", "M","M", "L","L","L","L"))
)
```

``` r
mean(pull(P1_df, random_sample))
```

    ## [1] 0.1322028

``` r
mean(pull(P1_df, sample_logical))
```

    ## [1] 0.6

``` r
mean(pull(P1_df, character_vector))
```

    ## Warning in mean.default(pull(P1_df, character_vector)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
mean(pull(P1_df, factor_vector))
```

    ## Warning in mean.default(pull(P1_df, factor_vector)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

**In this case, I could not get the mean of character\_vector and
factor\_vector since they are not numeric or logical.**

``` r
as.numeric(pull(P1_df, sample_logical))
```

    ##  [1] 0 1 0 1 1 0 1 1 1 0

``` r
as.numeric(pull(P1_df, character_vector))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(P1_df, factor_vector))
```

    ##  [1] 3 3 3 2 2 2 1 1 1 1

**In this case, it can be see that logical and factor could convert
variables to numerical variable and the character can not convert to
numerical variable.**

``` r
as.numeric(as.factor(P1_df$character_vector))
```

    ##  [1]  1  6 10  7  9  8  5  2  4  3

**In this case, it can be see that the character can be convert to
numerical.**

### Problem 2

**This problem focuses the use of inline R code, plotting, and the
behavior of ggplot for variables of different types.** **First, I
installed a package containing the penguins dataset.**

``` r
library(palmerpenguins)
```

``` r
data("penguins", package = "palmerpenguins")
```

-   Write a short description of the penguins dataset (not the
    penguins\_raw dataset) using inline R code, including:
    -   the data in this dataset, including names / values of important
        variables
    -   the size of the dataset (using nrow and ncol)
    -   the mean flipper length

``` r
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
mean(pull(penguins, flipper_length_mm ), na.rm=TRUE)
```

    ## [1] 200.9152

``` r
ncol(penguins)
```

    ## [1] 8

``` r
nrow(penguins)
```

    ## [1] 344

In the code Table: Data summary

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

, it summary some data information about the number of rows and columns,
column type frequency and different variable basic information. In the
code species, island, bill\_length\_mm, bill\_depth\_mm,
flipper\_length\_mm, body\_mass\_g, sex, year, it list the name of eight
different variables. Also, I could get the size of dataset by using 8
and 344. For the mean of the flipper length, I use the code 200.9152047
to get the mean and the mean is 200.9152.

``` r
ggplot(penguins,aes(x = bill_length_mm, y = flipper_length_mm, color = species))+ geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_fs2757_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

``` r
ggsave("ggplotQ2.pdf",height = 7, width = 7)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
